### ISSUE TITLE
Ops concerns for data.gov.au

### ISSUE THREAD

**Issue by kring** [TerriaJS/magda#214]
Some operations concerns for making MAGDA the main page of data.gov.au:
* [ ] Look at the usage/traffic of the concern site and make sure we can handle it.
* [ ] If data.gov.au has an existing SLA, make sure the new site can meet it.
* [ ] Work out how routing will work (i.e. both CKAN and MAGDA will serve URLs on data.gov.au)
