### ISSUE TITLE
MAGDA launch roadmap

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/magda#325]
This issue is to plan a rough roadmap for sequencing the epics to be worked on until the launch (approx. 30 June 2018). 

- [ ] Jan - Search; Home page (start collecting use cases) 

- [ ] Feb - Search; Data page

- [ ] Mar - Homepage (review and first design mockups); User management; User notifications

- [ ] Apr - Homepage (continue); User management; Prep for launch (planning) 

- [ ] May - Homepage; Data page; Feedback; Prep for launch (start development and installation)

- [ ] June - Finalise; test; deploy; Launch date 2 July (TBC) 

Roadmap view: 
![magda roadmap 2_jul17_jun18](https://user-images.githubusercontent.com/18452161/34857887-565fb86e-f7a1-11e7-8d8d-4fcce5106af0.JPG)

or here: 
https://confluence.csiro.au/display/DLGETD/MAGDA+-+DGA+project+plan

**Comment by tkeuneman** [comment]
Closing as this is documented elsewhere and we have epics and milestones that people can track.
